name: ProtocolSupportSwordBlocking
main: com.mrpowergamerbr.protocolsupportswordblocking.ProtocolSupportSwordBlocking
version: ${project.version}
authors: ["MrPowerGamerBR", "mikroskeem"]
depend: ["ProtocolSupport", "ProtocolLib"]